inpackage: False
with-expecter: True
packages:
  github.com/sebboness/yektaspoints/handlers:
    config:
      dir: "mocks/handlers"
    interfaces:
      AuthContext:
  github.com/sebboness/yektaspoints/storage:
    config:
      dir: "mocks/storage"
    interfaces:
      DynamoDbClient:
      IFamilyStorage:
      IPointsStorage:
      IUserStorage:
  github.com/sebboness/yektaspoints/util/auth:
    config:
      dir: "mocks/auth"
    interfaces:
      AuthController:
  github.com/sebboness/yektaspoints/util/jwt:
    config:
      dir: "mocks/jwt"
    interfaces:
      JwtParser: