AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lamda local demo

  
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: cmd/lambda/ # format is projectPath/
      Handler: bootstrap # format is filename.functionName
      Runtime: provided.al2023